/**
 * Locale strings owned by the rolling module (dice, roll buttons, the
 * roll panel, and the skills value type).
 */

import type { StringDict } from "../../i18n/i18n";

export const rollingEn: StringDict = {
  "roll.featureName": "Dice & rolls",
  "roll.featureDesc": "Roll buttons on properties, configurable dice (d2–d100 or custom), the roll log panel, and the skills data type.",

  "roll.roll": "Roll",
  "roll.rolls": "Rolls",
  "roll.checkLabel": "{name} check",
  "roll.tagAdvantage": "(adv)",
  "roll.tagDisadvantage": "(dis)",
  "roll.modeHint": "Roll mode — applies to all roll buttons",
  "roll.modeDisadvantage": "Disadv",
  "roll.modeNormal": "Normal",
  "roll.modeAdvantage": "Advantage",
  "roll.logEmpty": "Roll results will appear here.",

  "roll.options.rollButton": "Roll button",
  "roll.options.rollNone": "None",
  "roll.options.rollAbilityMod": "Modifier (dice + mod)",
  "roll.options.rollValue": "Value (dice + value)",
  "roll.options.rollSource": "Roll source",
  "roll.options.rollSourceDesc": "Property whose value the roll uses",
  "roll.options.rollSourceSelf": "(this property)",
  "roll.options.rollOverride": "Roll override",
  "roll.options.rollOverrideDesc": "Fixed modifier/value; blank derives from the source",

  "dice.die": "Die",
  "dice.dieDesc": "Preset die, or type a custom size next to it",
  "dice.custom": "Custom…",
  "dice.customSize": "Custom die size…",
  "dice.customSizePrompt": "Die size (number of faces)",
  "dice.customSizeShort": "size",
  "dice.count": "Number of dice…",
  "dice.countPrompt": "Number of dice",
  "dice.countLabel": "Number of dice",
  "dice.reset": "Default (d20)",

  "type.skills": "skills",
  "skills.empty": "No skills yet.",
  "skills.addMenu": "Add skills…",
  "skills.addSkill": "+ add skill",
  "skills.newSkill": "New skill…",
  "skills.newSkillPrompt": "Skill name",
  "skills.proficientHint": "Proficient",
  "skills.menu.addPreset": "Add preset: {name}",
  "skills.menu.setSource": "Set modifier source…",
  "skills.menu.setDice": "Set dice…",
  "skills.menu.clearOverride": "Clear modifier override",
  "skills.menu.moveUp": "Move up",
  "skills.menu.moveDown": "Move down",
  "skills.menu.remove": "Remove skill",
  "skills.options.heading": "Skills",
  "skills.options.editHint": "Rows are edited directly in the sidebar: click (or double-click outside edit mode) a name, source tag or modifier; right-click a row for dice, ordering and removal.",
  "skills.options.sourceMode": "Modifier from source",
  "skills.options.modeValue": "Source value as-is",
  "skills.options.modeAbilityMod": "Ability modifier ((value − 10) / 2)",
  "skills.options.profMode": "Proficiency bonus",
  "skills.options.profNone": "None",
  "skills.options.profLevel": "From a level property",
  "skills.options.profFixed": "Fixed value",
  "skills.options.profSource": "Level property",
  "skills.options.profFixedValue": "Bonus",
  "skills.options.presets": "Skill presets",
  "skills.options.addPreset": "Add",
};

export const rollingDe: StringDict = {
  "roll.featureName": "Würfel & Würfe",
  "roll.featureDesc": "Würfeln-Schaltflächen an Eigenschaften, konfigurierbare Würfel (W2–W100 oder eigene), das Wurfprotokoll und der Fertigkeiten-Datentyp.",

  "roll.roll": "Würfeln",
  "roll.rolls": "Würfe",
  "roll.checkLabel": "{name}-Probe",
  "roll.tagAdvantage": "(Vorteil)",
  "roll.tagDisadvantage": "(Nachteil)",
  "roll.modeHint": "Wurfmodus — gilt für alle Würfeln-Schaltflächen",
  "roll.modeDisadvantage": "Nachteil",
  "roll.modeNormal": "Normal",
  "roll.modeAdvantage": "Vorteil",
  "roll.logEmpty": "Wurfergebnisse erscheinen hier.",

  "roll.options.rollButton": "Würfeln-Schaltfläche",
  "roll.options.rollNone": "Keine",
  "roll.options.rollAbilityMod": "Modifikator (Würfel + Mod)",
  "roll.options.rollValue": "Wert (Würfel + Wert)",
  "roll.options.rollSource": "Wurfquelle",
  "roll.options.rollSourceDesc": "Eigenschaft, deren Wert der Wurf verwendet",
  "roll.options.rollSourceSelf": "(diese Eigenschaft)",
  "roll.options.rollOverride": "Fester Wurfwert",
  "roll.options.rollOverrideDesc": "Fester Modifikator/Wert; leer = aus der Quelle abgeleitet",

  "dice.die": "Würfel",
  "dice.dieDesc": "Vordefinierter Würfel, oder eigene Größe daneben eintragen",
  "dice.custom": "Eigene…",
  "dice.customSize": "Eigene Würfelgröße…",
  "dice.customSizePrompt": "Würfelgröße (Anzahl Seiten)",
  "dice.customSizeShort": "Größe",
  "dice.count": "Anzahl Würfel…",
  "dice.countPrompt": "Anzahl Würfel",
  "dice.countLabel": "Anzahl Würfel",
  "dice.reset": "Standard (W20)",

  "type.skills": "Fertigkeiten",
  "skills.empty": "Noch keine Fertigkeiten.",
  "skills.addMenu": "Fertigkeiten hinzufügen…",
  "skills.addSkill": "+ Fertigkeit hinzufügen",
  "skills.newSkill": "Neue Fertigkeit…",
  "skills.newSkillPrompt": "Name der Fertigkeit",
  "skills.proficientHint": "Geübt",
  "skills.menu.addPreset": "Vorlage hinzufügen: {name}",
  "skills.menu.setSource": "Modifikator-Quelle festlegen…",
  "skills.menu.setDice": "Würfel festlegen…",
  "skills.menu.clearOverride": "Modifikator-Überschreibung entfernen",
  "skills.menu.moveUp": "Nach oben",
  "skills.menu.moveDown": "Nach unten",
  "skills.menu.remove": "Fertigkeit entfernen",
  "skills.options.heading": "Fertigkeiten",
  "skills.options.editHint": "Zeilen werden direkt in der Seitenleiste bearbeitet: Name, Quellen-Kürzel oder Modifikator anklicken (außerhalb des Bearbeitungsmodus doppelklicken); Rechtsklick für Würfel, Reihenfolge und Entfernen.",
  "skills.options.sourceMode": "Modifikator aus der Quelle",
  "skills.options.modeValue": "Quellwert unverändert",
  "skills.options.modeAbilityMod": "Attributsmodifikator ((Wert − 10) / 2)",
  "skills.options.profMode": "Übungsbonus",
  "skills.options.profNone": "Keiner",
  "skills.options.profLevel": "Aus einer Stufen-Eigenschaft",
  "skills.options.profFixed": "Fester Wert",
  "skills.options.profSource": "Stufen-Eigenschaft",
  "skills.options.profFixedValue": "Bonus",
  "skills.options.presets": "Fertigkeiten-Vorlagen",
  "skills.options.addPreset": "Hinzufügen",
};
